- name: accuracy_top1
  config:
    _target_: torchrecipes.vision.image_classification.metrics.multilabel_accuracy.MultilabelAccuracy
    top_k: 1
- name: accuracy_top5
  config:
    _target_: torchrecipes.vision.image_classification.metrics.multilabel_accuracy.MultilabelAccuracy
    top_k: 5
