_target_: torchrecipes.text.doc_classification.train_app.DocClassificationTrainApp

defaults:
  - _self_
  # module
  - schema/module: doc_classification
  - module/optim: adamw
  - module/model: xlmrbase_classifier
  # datamodule
  - schema/datamodule: doc_classification
  - datamodule: doc_classification_datamodule
  - datamodule/dataset: sst2_dataset
  # trainer
  - schema/trainer: trainer
  - trainer: cpu
  # transform
  - transform: doc_classification_transform

hydra:
  searchpath:
    - pkg://torchrecipes.text.doc_classification.datamodule
    - pkg://torchrecipes.text.doc_classification.module
    - pkg://torchrecipes.text.doc_classification.transform
    - pkg://torchrecipes.core.conf
